Simplify the ValuesAttribute
nunit/nunit.analyzers pull request #758
Opened 2024-06-09 18:04 UTC by Bartleby2718

This is my first time adding a new diagnostic, please take a closer look at Markdown file changes or strings that users can see. Thanks in advance!

2024-06-11 04:12 UTC, manfred-brands requested changes
Nice work, I only have some small comments.

2024-06-11 04:12 UTC, manfred-brands commented on src/nunit.analyzers/SimplifyValues/SimplifyValuesCodeFix.cs
> +        => ImmutableArray.Create(AnalyzerIdentifiers.SimplifyValues);
```suggestion
    public override ImmutableArray<string> FixableDiagnosticIds { get; }
        = ImmutableArray.Create(AnalyzerIdentifiers.SimplifyValues);
```

The original version would create a new instance every time it is called.
Yes, I know not all the Analyzer use this (yet)

2024-06-16 18:25 UTC, Bartleby2718 commented on src/nunit.analyzers/SimplifyValues/SimplifyValuesAnalyzerConstants.cs
> +    internal const string SimplifyValuesDescription = "Consider simplifying the ValuesAttribute when you're using the CombinatorialAttribute.";
@manfred-brands I believe this should match https://github.com/nunit/nunit.analyzers/pull/758#discussion_r1634114854; which one do you prefer?

2024-06-16 19:56 UTC, Bartleby2718 commented on src/nunit.analyzers.tests/SimplifyValues/SimplifyValuesAnalyzerTests.cs
> +        public void Test([Values(new object[] { true })] bool b) { }
> Would anybody write such code?

I wouldn't, but I was just doing the same thing as in [`ValuesUsageAnalyzerTests.cs`](https://github.com/nunit/nunit.analyzers/blob/master/src/nunit.analyzers.tests/ValuesUsage/ValuesUsageAnalyzerTests.cs).

> add a test case for this

If I do, I get [CS0182: An attribute argument must be a constant expression, typeof expression or array creation expression of an attribute parameter type](https://learn.microsoft.com/en-us/dotnet/csharp/language-reference/compiler-messages/parameter-argument-mismatch#arguments-for-attributes) for the test, so we can safely ignore this case.

### Would you like me to drop support for the array creation expression? I'd be happy to do that.

2024-06-17 14:51 UTC, manfred-brands commented on src/nunit.analyzers.tests/SimplifyValues/SimplifyValuesAnalyzerTests.cs
> +        public void Test([Values(new object[] { true })] bool b) { }
As you already did the work for the array creation expression, leave it in for now.

2024-06-17 16:38 UTC, Bartleby2718 commented on documentation/NUnit4001.md
> +Consider simplifying the ValuesAttribute when you're using the CombinatorialAttribute.
Closing in favor of https://github.com/nunit/nunit.analyzers/pull/758#discussion_r1634123798

2024-06-18 08:15 UTC, manfred-brands approved these changes
Two nitpicks, nothing else.

2024-06-18 08:15 UTC, manfred-brands commented on src/nunit.analyzers/SimplifyValues/SimplifyValuesAnalyzer.cs
> +            .Any(attribute => attribute.AttributeClass is { } attributeClass
I find `is { }` very hard to read. 
```suggestion
            .Any(attribute => attribute.AttributeClass is INamedTypeSymbol attributeClass
```

2024-06-18 08:15 UTC, manfred-brands commented on src/nunit.analyzers/SimplifyValues/SimplifyValuesAnalyzer.cs
> +                && StringComparer.OrdinalIgnoreCase.Equals(
We don't want 'nunit.framework' to match. 
```suggestion
                && StringComparer.Ordinal.Equals(
```

2024-06-20 08:51 UTC, merged

2024-06-20 08:51 UTC, manfred-brands commented
Thanks @Bartleby2718, I have merged the PR now.

2024-06-20 09:41 UTC, Bartleby2718 commented
@manfred-brands Thanks for providing feedback and merging the PR!