Use Assert.ThatAsync
nunit/nunit.analyzers pull request #804
Opened 2024-12-06 01:06 UTC by Bartleby2718

This closes #759.

2024-12-06 02:20 UTC, manfred-brands requested changes
Although the PR fixes what #759 describes it is for the wrong reason.
None of the examples do async-over-sync.

It fixes a style issue and at most should be a `suggestion` or even disabled by default.
This allows you to use this rule, but don't force it on others.
If you were mistaken and you thought this was doing synchronous async we could drop it.

What we could use is a rule that detects the real use-cases where we do synchronous async calls which is the examples mentioned in my comments.
This could be a separate diagnostic supported by the same Analyzer/CodeFix pair.

2024-12-06 02:20 UTC, manfred-brands commented on src/nunit.analyzers.tests/UseAssertThatAsync/UseAssertThatAsyncCodeFixTests.cs
> +}
Please add an example for detecting:
```csharp
public void Test()
{
    Assert.That(() => Task.FromException<int>(new InvalidOperationException()), Throws.InvalidOperationException);
}
```
With a code fix looking like:
```csharp
public async Task Test()
{
    await Assert.ThatAsync(() => Task.FromException<int>(new InvalidOperationException()), Throws.InvalidOperationException);
}
```

Especially notice the need to change the return type of the test from `void` to `async Task`.

2024-12-06 02:20 UTC, manfred-brands commented on src/nunit.analyzers/UseAssertThatAsync/UseAssertThatAsyncAnalyzer.cs
> +        // The first parameter is usually the "actual" parameter, but sometimes it's the "condition" parameter.
The only argument name we want to catch is actually called `del` as used in:
` public static void That<TActual>(ActualValueDelegate<TActual> del, IResolveConstraint expr`

2024-12-06 02:20 UTC, manfred-brands commented on src/nunit.analyzers/UseAssertThatAsync/UseAssertThatAsyncAnalyzer.cs
> +        if (actualArgument.Syntax is not ArgumentSyntax argumentSyntax || argumentSyntax.Expression is not AwaitExpressionSyntax awaitExpression)
When the argument is _awaited_ then NUnit doesn't do async-over-sync.

2024-12-06 03:12 UTC, Bartleby2718 commented
Thanks for the quick feedback @manfred-brands!

Besides the overload you mentioned [here](https://github.com/nunit/nunit.analyzers/pull/804#discussion_r1872469762), am I correct in assuming that the following overloads should also be converted?
```cs
public static void That(Func<bool> condition, NUnitString message, string actualExpression)
public static void That(TestDelegate code, IResolveConstraint constraint, NUnitString message, string actualExpression, string constraintExpression)
```

2024-12-06 03:23 UTC, manfred-brands commented
> Thanks for the quick feedback @manfred-brands!
> 
> Besides the overload you mentioned [here](https://github.com/nunit/nunit.analyzers/pull/804#discussion_r1872469762), am I correct in assuming that the following overloads should also be converted?
> 
> ```cs
> public static void That(Func<bool> condition, NUnitString message, string actualExpression)
> public static void That(TestDelegate code, IResolveConstraint constraint, NUnitString message, string actualExpression, string constraintExpression)
> ```

The first no. As NUnit calls `condition.Invoke()` and the code wouldn't accept an `Func<Task<bool>>`.
The second yes. So also test for parameter name _code_.

2025-01-27 00:47 UTC, manfred-brands commented
@Bartleby2718 Will you continue with this PR or closes it as the use-cases you highlighted were not actually doing async-over-sync.

2025-01-27 01:27 UTC, closed without merging

2025-01-27 01:28 UTC, Bartleby2718 commented
@manfred-brands I don't think I'll be able to get to this soon, so I've closed the PR.